export const HallDetails = [
  {
    id: 1,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 1,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 1,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 1,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lecture Hall 2",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lecture Hall 3",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lecture Hall 4",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lecture Hall 1",
    capacity: 100,
    location: "1st Floor",
  },
];

export const LabDetails = [
  {
    id: 1,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 1,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 1,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 1,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 2,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 3,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 4,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
  {
    id: 5,
    name: "Lab 1",
    capacity: 100,
    location: "1st Floor",
  },
];
