export const ClassRooms = [
  {
    Id: 1,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    resources: [],
    classRoomType: 0,
  },
  {
    Id: 2,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    labType: "Hardware",
    resources: [
      {
        Id: 1,
        ResourceName: "Hardware",
        Quantity: 10,
      },
      {
        Id: 2,
        ResourceName: "Hardware",
        Quantity: 10,
      },
    ],
    classRoomType: 1,
  },
  {
    Id: 3,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    resources: [],
    classRoomType: 0,
  },
  {
    Id: 4,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    labType: "Mechanics",
    resources: [
      {
        Id: 2,
        ResourceName: "Car Simulator",
        Quantity: 1,
      },
      {
        Id: 3,
        ResourceName: "Car Simulator",
        Quantity: 1,
      },
    ],
    classRoomType: 1,
  },
  {
    Id: 5,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    labType: "Software",
    resources: [
      {
        Id: 3,
        ResourceName: "Computer",
        Quantity: 10,
      },
    ],
    classRoomType: 1,
  },

  {
    Id: 6,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    labType: "Computer Lab",
    resources: [
      {
        Id: 4,
        ResourceName: "Computer",
        Quantity: 10,
      },
    ],
    classRoomType: 1,
  },
  {
    Id: 7,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    resources: [],
    classRoomType: 0,
  },
  {
    Id: 8,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    labType: "Software Engineering",
    resources: [
      {
        Id: 5,
        ResourceName: "Computer",
        Quantity: 40,
      },
      {
        Id: 11,
        ResourceName: "Printer",
        Quantity: 40,
      },
    ],
    classRoomType: 1,
  },
  {
    Id: 9,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    resources: [],
    classRoomType: 0,
  },
  {
    Id: 10,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    labType: "COmputer",
    resources: [
      {
        Id: 5,
        ResourceName: "Computer",
        Quantity: 10,
      },
    ],
    classRoomType: 1,
  },
  {
    Id: 11,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    resources: [],
    classRoomType: 0,
  },
  {
    Id: 12,
    FloorNumber: 1,
    BuildingNumber: 1,
    capacity: 100,
    resources: [],
    classRoomType: 0,
  },
];
